services:
  db:
    image: postgres:16-alpine
    container_name: pintofruta-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: pintofruta
      POSTGRES_PASSWORD: pintofruta
      POSTGRES_DB: pintofruta_store
    volumes:
      - pintofruta_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pintofruta -d pintofruta_store"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pintofruta_postgres_data:
